USE QuanLyBanHang
GO

--2--
ALTER TABLE SANPHAM
ADD GHICHU varchar(20);

--3--
ALTER TABLE KHACHHANG
ADD LOAIKH tinyint;

--4--
ALTER TABLE SANPHAM
ALTER COLUMN GHICHU varchar(100);

--5--
ALTER TABLE SANPHAM
DROP COLUMN GHICHU;

--6--
ALTER TABLE KHACHHANG
ALTER COLUMN LOAIKH varchar(20);

--7--
ALTER TABLE SANPHAM
ADD CONSTRAINT chk_don_vi_tinh
CHECK (DVT IN ('cay', 'hop', 'cai', 'quyen', 'chuc'));

--8--
ALTER TABLE SANPHAM
ADD CONSTRAINT chk_gia
CHECK (GIA >= 500);

--9--
ALTER TABLE CTHD
ADD CONSTRAINT chk_sl
CHECK (SL >= 1);

--10--
ALTER TABLE KHACHHANG
ADD CONSTRAINT chk_ngdk
CHECK (NGDK > NGSINH);
